#!/bin/bash



#######################
# FUNCTIONS
################
function errorParametros(){
  echo "Error, nº de parámetros incorrecto." 1>&2
  echo "Con --help se mostrará la ayuda." 1>&2
  exit 1
}


function errorPrimerParametro(){
  echo "Error, el primer parámetro ($1) no es válido." 1>&2
  echo "Con --help se mostrará la ayuda." 1>&2
  exit 2
}

function errorPrimerParametroNoEsUnNumero(){
  echo "Error, el primer parámetro no es un número" 1>&2
  exit 3
}





function error(){
  case $1 in
    1) echo "Error, nº de parámetros incorrecto.";;
    2) echo "Error, el primer parámetro no es válido." 1>&2;;
    3) echo "Error, el primer parámetro no es un número" 1>&2;;
    4) echo "Error, blablabalbalbalba" 1>&2;;
    *) echo "Error indefinido" 1>&2
  esac

  echo "Con --help se mostrará la ayuda." 1>&2
  exit $1
}



function ayuda(){
  echo "Permite llevar el control de los gastos básicos."
  echo
  echo "Uso: $0 --help|lista|borrar"
  echo "Uso: $0 cantidad concepto"
  echo
  echo "Parámetros:"
  echo "   --help    : muestra esta ayuda"
  echo "   lista     : muestra los gastos almacenados"
  echo "   borrar    : borra todos los gastos almacenados"
  echo "   cantidad  : el coste del concepto de gasto (por ejemplo: 14)"
  echo "   concepto  : el gasto que se desea almacenar (por ejemplo: gasolina)"
  echo
  echo "Ejemplo:"
  echo "$0 160 \"compra en el supermercado\""
  exit 0
}


function lista(){
  # Si recibe un único parámetro y es `lista` mostrará el contenido del fichero `gastos.txt`. Si el fichero no existe mostrará un mensaje indicándolo.
  
  if [ -f "gastos.txt" ];then
    echo "   Gastos | Concepto"
    echo "----------|-------------------"
    cat gastos.txt
  else
    echo "El fichero de gastos (gastos.txt) no existe todavía";
  fi

  exit 0
}



function borrar(){
  rm gastos.txt 2>/dev/null
  exit 0
}



#######################
# MAIN
################

#Comprobamos los parámetros
# [ $# -gt 2 ] && errorParametros
[ $# -gt 2 ] && error 1
# [ $# -eq 0 ] && errorParametros
[ $# -eq 0 ] && error 2

[ $# -eq 1 ] && [ "$1" == "--help" ] && ayuda
[ $# -eq 1 ] && [ "$1" == "lista" ] && lista
[ $# -eq 1 ] && [ "$1" == "borrar" ] && borrar

[ $# -eq 1 ] && errorPrimerParametro $1


if [ $# -eq 2 ];then
  ./esNum $1
  # [ $? -eq 1 ] && errorPrimerParametroNoEsUnNumero
  [ $? -eq 1 ] && error 3
fi


# Si llego aquí sé que se reciben dos parámetros y el primero es un número
# echo $1 $2 >> gastos.txt
printf "%7d € | $2\n" $1 >> gastos.txt

# *Nota:* Si quieres que quede tabulado perfectamente puedes usar `printf "%7d" 245` en lugar de `echo "245"`. Eso añade los espacios necesarios para que el `245` ocupe 7 caracteres, es decir, imprimirá `    245`.






# ```sh
# $ ./controlgastos
# Error: número de parámetros incorrecto. Use --help para ver la ayuda.

# $ ./controlgastos gato zorro
# Error: el primer parámetro debe ser un número.

# $ ./controlgastos 12 "móvil"
# $ ./controlgastos 160 "compra en el supermercado"
# $ ./controlgastos 55 "electricidad"

# $ ./controlgastos lista
#    Gastos | Concepto
# ---------------------------------
#      12 € | móvil
#     160 € | compra en el supermercado
#      55 € | electricidad

# $ ./controlgastos borrar
# $ ./controlgastos lista
# No hay datos que mostrar.
# ```



